/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomType = IDL.Record({
  'bedCount' : IDL.Nat,
  'deposit' : IDL.Nat,
  'availableBeds' : IDL.Nat,
  'price' : IDL.Nat,
  'roomType' : IDL.Text,
});
export const Booking = IDL.Record({
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'name' : IDL.Text,
  'pgId' : IDL.Text,
  'user' : IDL.Principal,
  'phone' : IDL.Text,
  'moveInDate' : IDL.Text,
  'roomType' : RoomType,
});
export const Amenities = IDL.Record({
  'ac' : IDL.Bool,
  'gym' : IDL.Bool,
  'cleaning' : IDL.Bool,
  'food' : IDL.Bool,
  'wifi' : IDL.Bool,
  'security' : IDL.Bool,
  'powerBackup' : IDL.Bool,
  'parking' : IDL.Bool,
  'laundry' : IDL.Bool,
  'hotWater' : IDL.Bool,
});
export const Address = IDL.Record({
  'country' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'fullAddress' : IDL.Text,
  'pincode' : IDL.Nat,
});
export const GeoLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const PGListing = IDL.Record({
  'latitude' : IDL.Float64,
  'verified' : IDL.Bool,
  'foodIncluded' : IDL.Bool,
  'wifiSpeed' : IDL.Nat,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'acAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'deposit' : IDL.Nat,
  'amenities' : Amenities,
  'cleanlinessScore' : IDL.Float64,
  'availableBeds' : IDL.Nat,
  'longitude' : IDL.Float64,
  'address' : Address,
  'gender' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'sharingTypes' : IDL.Vec(IDL.Text),
  'foodScore' : IDL.Float64,
  'geoLocation' : IDL.Opt(GeoLocation),
  'rooms' : IDL.Vec(RoomType),
  'images' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'foodRating' : IDL.Nat,
  'pgId' : IDL.Text,
  'user' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'safetyRating' : IDL.Nat,
  'rating' : IDL.Nat,
  'valueRating' : IDL.Nat,
  'cleanlinessRating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(Address),
  'gender' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBooking' : IDL.Func(
      [Booking],
      [IDL.Record({ 'id' : IDL.Text, 'booking' : Booking })],
      [],
    ),
  'addPGListing' : IDL.Func([IDL.Text, PGListing], [], []),
  'addReview' : IDL.Func([Review], [IDL.Text], []),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'deletePGListing' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'getAllPGListings' : IDL.Func([], [IDL.Vec(PGListing)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingListings' : IDL.Nat,
          'verifiedListings' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'totalListings' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalReviews' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getBookingsByPG' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPGListing' : IDL.Func([IDL.Text], [IDL.Opt(PGListing)], ['query']),
  'getPGListingsByAmenities' : IDL.Func(
      [Amenities],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsByArea' : IDL.Func([IDL.Text], [IDL.Vec(PGListing)], ['query']),
  'getPGListingsByAreaAndGender' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsByAreaAndSharingType' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsByCity' : IDL.Func([IDL.Text], [IDL.Vec(PGListing)], ['query']),
  'getPGListingsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsSortedByPrice' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsSortedByRating' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsWithAC' : IDL.Func([IDL.Bool], [IDL.Vec(PGListing)], ['query']),
  'getPGListingsWithAvailableBeds' : IDL.Func(
      [],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsWithFoodIncluded' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getPGListingsWithMinRating' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(PGListing)],
      ['query'],
    ),
  'getReviewsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getReviewsForPG' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserWishlist' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getVerifiedPGListings' : IDL.Func([], [IDL.Vec(PGListing)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPGListings' : IDL.Func([IDL.Text], [IDL.Vec(PGListing)], ['query']),
  'updatePGListing' : IDL.Func([IDL.Text, PGListing], [], []),
  'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomType = IDL.Record({
    'bedCount' : IDL.Nat,
    'deposit' : IDL.Nat,
    'availableBeds' : IDL.Nat,
    'price' : IDL.Nat,
    'roomType' : IDL.Text,
  });
  const Booking = IDL.Record({
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'name' : IDL.Text,
    'pgId' : IDL.Text,
    'user' : IDL.Principal,
    'phone' : IDL.Text,
    'moveInDate' : IDL.Text,
    'roomType' : RoomType,
  });
  const Amenities = IDL.Record({
    'ac' : IDL.Bool,
    'gym' : IDL.Bool,
    'cleaning' : IDL.Bool,
    'food' : IDL.Bool,
    'wifi' : IDL.Bool,
    'security' : IDL.Bool,
    'powerBackup' : IDL.Bool,
    'parking' : IDL.Bool,
    'laundry' : IDL.Bool,
    'hotWater' : IDL.Bool,
  });
  const Address = IDL.Record({
    'country' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'fullAddress' : IDL.Text,
    'pincode' : IDL.Nat,
  });
  const GeoLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const PGListing = IDL.Record({
    'latitude' : IDL.Float64,
    'verified' : IDL.Bool,
    'foodIncluded' : IDL.Bool,
    'wifiSpeed' : IDL.Nat,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'acAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'deposit' : IDL.Nat,
    'amenities' : Amenities,
    'cleanlinessScore' : IDL.Float64,
    'availableBeds' : IDL.Nat,
    'longitude' : IDL.Float64,
    'address' : Address,
    'gender' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'sharingTypes' : IDL.Vec(IDL.Text),
    'foodScore' : IDL.Float64,
    'geoLocation' : IDL.Opt(GeoLocation),
    'rooms' : IDL.Vec(RoomType),
    'images' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'foodRating' : IDL.Nat,
    'pgId' : IDL.Text,
    'user' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'safetyRating' : IDL.Nat,
    'rating' : IDL.Nat,
    'valueRating' : IDL.Nat,
    'cleanlinessRating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(Address),
    'gender' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBooking' : IDL.Func(
        [Booking],
        [IDL.Record({ 'id' : IDL.Text, 'booking' : Booking })],
        [],
      ),
    'addPGListing' : IDL.Func([IDL.Text, PGListing], [], []),
    'addReview' : IDL.Func([Review], [IDL.Text], []),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'deletePGListing' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'getAllPGListings' : IDL.Func([], [IDL.Vec(PGListing)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingListings' : IDL.Nat,
            'verifiedListings' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'totalListings' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalReviews' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getBookingsByPG' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPGListing' : IDL.Func([IDL.Text], [IDL.Opt(PGListing)], ['query']),
    'getPGListingsByAmenities' : IDL.Func(
        [Amenities],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsByArea' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsByAreaAndGender' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsByAreaAndSharingType' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsSortedByPrice' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsSortedByRating' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsWithAC' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsWithAvailableBeds' : IDL.Func(
        [],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsWithFoodIncluded' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getPGListingsWithMinRating' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(PGListing)],
        ['query'],
      ),
    'getReviewsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getReviewsForPG' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserWishlist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getVerifiedPGListings' : IDL.Func([], [IDL.Vec(PGListing)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPGListings' : IDL.Func([IDL.Text], [IDL.Vec(PGListing)], ['query']),
    'updatePGListing' : IDL.Func([IDL.Text, PGListing], [], []),
    'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };