/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'country' : string,
  'area' : string,
  'city' : string,
  'state' : string,
  'fullAddress' : string,
  'pincode' : bigint,
}
export interface Amenities {
  'ac' : boolean,
  'gym' : boolean,
  'cleaning' : boolean,
  'food' : boolean,
  'wifi' : boolean,
  'security' : boolean,
  'powerBackup' : boolean,
  'parking' : boolean,
  'laundry' : boolean,
  'hotWater' : boolean,
}
export interface Booking {
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'confirmed' : null },
  'name' : string,
  'pgId' : string,
  'user' : Principal,
  'phone' : string,
  'moveInDate' : string,
  'roomType' : RoomType,
}
export interface GeoLocation { 'latitude' : number, 'longitude' : number }
export interface PGListing {
  'latitude' : number,
  'verified' : boolean,
  'foodIncluded' : boolean,
  'wifiSpeed' : bigint,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'acAvailable' : boolean,
  'description' : string,
  'deposit' : bigint,
  'amenities' : Amenities,
  'cleanlinessScore' : number,
  'availableBeds' : bigint,
  'longitude' : number,
  'address' : Address,
  'gender' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'sharingTypes' : Array<string>,
  'foodScore' : number,
  'geoLocation' : [] | [GeoLocation],
  'rooms' : Array<RoomType>,
  'images' : Array<string>,
}
export interface Review {
  'foodRating' : bigint,
  'pgId' : string,
  'user' : Principal,
  'comment' : string,
  'timestamp' : Time,
  'safetyRating' : bigint,
  'rating' : bigint,
  'valueRating' : bigint,
  'cleanlinessRating' : bigint,
}
export interface RoomType {
  'bedCount' : bigint,
  'deposit' : bigint,
  'availableBeds' : bigint,
  'price' : bigint,
  'roomType' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [Address],
  'gender' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBooking' : ActorMethod<[Booking], { 'id' : string, 'booking' : Booking }>,
  'addPGListing' : ActorMethod<[string, PGListing], undefined>,
  'addReview' : ActorMethod<[Review], string>,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deletePGListing' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'getAllPGListings' : ActorMethod<[], Array<PGListing>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'pendingListings' : bigint,
      'verifiedListings' : bigint,
      'totalBookings' : bigint,
      'totalListings' : bigint,
      'totalUsers' : bigint,
      'totalReviews' : bigint,
    }
  >,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'getBookingsByPG' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByUser' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPGListing' : ActorMethod<[string], [] | [PGListing]>,
  'getPGListingsByAmenities' : ActorMethod<[Amenities], Array<PGListing>>,
  'getPGListingsByArea' : ActorMethod<[string], Array<PGListing>>,
  'getPGListingsByAreaAndGender' : ActorMethod<
    [string, string],
    Array<PGListing>
  >,
  'getPGListingsByAreaAndSharingType' : ActorMethod<
    [string, string],
    Array<PGListing>
  >,
  'getPGListingsByCity' : ActorMethod<[string], Array<PGListing>>,
  'getPGListingsByOwner' : ActorMethod<[Principal], Array<PGListing>>,
  'getPGListingsByPriceRange' : ActorMethod<[bigint, bigint], Array<PGListing>>,
  'getPGListingsSortedByPrice' : ActorMethod<[string], Array<PGListing>>,
  'getPGListingsSortedByRating' : ActorMethod<[string], Array<PGListing>>,
  'getPGListingsWithAC' : ActorMethod<[boolean], Array<PGListing>>,
  'getPGListingsWithAvailableBeds' : ActorMethod<[], Array<PGListing>>,
  'getPGListingsWithFoodIncluded' : ActorMethod<[boolean], Array<PGListing>>,
  'getPGListingsWithMinRating' : ActorMethod<[number], Array<PGListing>>,
  'getReviewsByUser' : ActorMethod<[Principal], Array<Review>>,
  'getReviewsForPG' : ActorMethod<[string], Array<Review>>,
  'getUserBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserWishlist' : ActorMethod<[Principal], Array<string>>,
  'getVerifiedPGListings' : ActorMethod<[], Array<PGListing>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPGListings' : ActorMethod<[string], Array<PGListing>>,
  'updatePGListing' : ActorMethod<[string, PGListing], undefined>,
  'updateUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];