/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    foodRating: bigint;
    pgId: string;
    user: Principal;
    comment: string;
    timestamp: Time;
    safetyRating: bigint;
    rating: bigint;
    valueRating: bigint;
    cleanlinessRating: bigint;
}
export interface GeoLocation {
    latitude: number;
    longitude: number;
}
export interface PGListing {
    latitude: number;
    verified: boolean;
    foodIncluded: boolean;
    wifiSpeed: bigint;
    owner: Principal;
    city: string;
    name: string;
    acAvailable: boolean;
    description: string;
    deposit: bigint;
    amenities: Amenities;
    cleanlinessScore: number;
    availableBeds: bigint;
    longitude: number;
    address: Address;
    gender: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    sharingTypes: Array<string>;
    foodScore: number;
    geoLocation?: GeoLocation;
    rooms: Array<RoomType>;
    images: Array<string>;
}
export type Time = bigint;
export interface Amenities {
    ac: boolean;
    gym: boolean;
    cleaning: boolean;
    food: boolean;
    wifi: boolean;
    security: boolean;
    powerBackup: boolean;
    parking: boolean;
    laundry: boolean;
    hotWater: boolean;
}
export interface Address {
    country: string;
    area: string;
    city: string;
    state: string;
    fullAddress: string;
    pincode: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Booking {
    status: Variant_cancelled_pending_confirmed;
    name: string;
    pgId: string;
    user: Principal;
    phone: string;
    moveInDate: string;
    roomType: RoomType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RoomType {
    bedCount: bigint;
    deposit: bigint;
    availableBeds: bigint;
    price: bigint;
    roomType: string;
}
export interface UserProfile {
    name: string;
    email?: string;
    address?: Address;
    gender?: string;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_pending_confirmed {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBooking(booking: Booking): Promise<{
        id: string;
        booking: Booking;
    }>;
    addPGListing(id: string, listing: PGListing): Promise<void>;
    addReview(review: Review): Promise<string>;
    addToWishlist(pgId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBooking(id: string): Promise<void>;
    deletePGListing(id: string): Promise<void>;
    deleteReview(id: string): Promise<void>;
    getAllPGListings(): Promise<Array<PGListing>>;
    getAnalytics(): Promise<{
        pendingListings: bigint;
        verifiedListings: bigint;
        totalBookings: bigint;
        totalListings: bigint;
        totalUsers: bigint;
        totalReviews: bigint;
    }>;
    getBooking(id: string): Promise<Booking | null>;
    getBookingsByPG(pgId: string): Promise<Array<Booking>>;
    getBookingsByUser(userId: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getPGListing(id: string): Promise<PGListing | null>;
    getPGListingsByAmenities(required: Amenities): Promise<Array<PGListing>>;
    getPGListingsByArea(area: string): Promise<Array<PGListing>>;
    getPGListingsByAreaAndGender(area: string, gender: string): Promise<Array<PGListing>>;
    getPGListingsByAreaAndSharingType(area: string, sharingType: string): Promise<Array<PGListing>>;
    getPGListingsByCity(city: string): Promise<Array<PGListing>>;
    getPGListingsByOwner(owner: Principal): Promise<Array<PGListing>>;
    getPGListingsByPriceRange(min: bigint, max: bigint): Promise<Array<PGListing>>;
    getPGListingsSortedByPrice(sortOrder: string): Promise<Array<PGListing>>;
    getPGListingsSortedByRating(sortOrder: string): Promise<Array<PGListing>>;
    getPGListingsWithAC(acAvailable: boolean): Promise<Array<PGListing>>;
    getPGListingsWithAvailableBeds(): Promise<Array<PGListing>>;
    getPGListingsWithFoodIncluded(foodIncluded: boolean): Promise<Array<PGListing>>;
    getPGListingsWithMinRating(minRating: number): Promise<Array<PGListing>>;
    getReviewsByUser(user: Principal): Promise<Array<Review>>;
    getReviewsForPG(pgId: string): Promise<Array<Review>>;
    getUserBookings(user: Principal): Promise<Array<Booking>>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    getUserWishlist(user: Principal): Promise<Array<string>>;
    getVerifiedPGListings(): Promise<Array<PGListing>>;
    isCallerAdmin(): Promise<boolean>;
    removeFromWishlist(pgId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPGListings(searchText: string): Promise<Array<PGListing>>;
    updatePGListing(id: string, listing: PGListing): Promise<void>;
    updateUserProfile(user: Principal, profile: UserProfile): Promise<void>;
}
import type { Address as _Address, Amenities as _Amenities, Booking as _Booking, GeoLocation as _GeoLocation, PGListing as _PGListing, RoomType as _RoomType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBooking(arg0: Booking): Promise<{
        id: string;
        booking: Booking;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addBooking(to_candid_Booking_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBooking(to_candid_Booking_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPGListing(arg0: string, arg1: PGListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPGListing(arg0, to_candid_PGListing_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPGListing(arg0, to_candid_PGListing_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addReview(arg0: Review): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addToWishlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deletePGListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePGListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePGListing(arg0);
            return result;
        }
    }
    async deleteReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getAllPGListings(): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPGListings();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPGListings();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<{
        pendingListings: bigint;
        verifiedListings: bigint;
        totalBookings: bigint;
        totalListings: bigint;
        totalUsers: bigint;
        totalReviews: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getBooking(arg0: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByPG(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPG(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPG(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByUser(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListing(arg0: string): Promise<PGListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListing(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListing(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByAmenities(arg0: Amenities): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByAmenities(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByAmenities(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByArea(arg0: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByArea(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByArea(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByAreaAndGender(arg0: string, arg1: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByAreaAndGender(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByAreaAndGender(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByAreaAndSharingType(arg0: string, arg1: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByAreaAndSharingType(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByAreaAndSharingType(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByCity(arg0: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByCity(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByCity(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByOwner(arg0: Principal): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByOwner(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByOwner(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsByPriceRange(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsByPriceRange(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsSortedByPrice(arg0: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsSortedByPrice(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsSortedByPrice(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsSortedByRating(arg0: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsSortedByRating(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsSortedByRating(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsWithAC(arg0: boolean): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsWithAC(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsWithAC(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsWithAvailableBeds(): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsWithAvailableBeds();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsWithAvailableBeds();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsWithFoodIncluded(arg0: boolean): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsWithFoodIncluded(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsWithFoodIncluded(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPGListingsWithMinRating(arg0: number): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPGListingsWithMinRating(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPGListingsWithMinRating(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByUser(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByUser(arg0);
            return result;
        }
    }
    async getReviewsForPG(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForPG(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForPG(arg0);
            return result;
        }
    }
    async getUserBookings(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWishlist(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWishlist(arg0);
            return result;
        }
    }
    async getVerifiedPGListings(): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedPGListings();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedPGListings();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFromWishlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPGListings(arg0: string): Promise<Array<PGListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPGListings(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPGListings(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePGListing(arg0: string, arg1: PGListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePGListing(arg0, to_candid_PGListing_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePGListing(arg0, to_candid_PGListing_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserProfile(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Booking_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PGListing_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PGListing): PGListing {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeoLocation]): GeoLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Address]): Address | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PGListing]): PGListing | null {
    return value.length === 0 ? null : from_candid_PGListing_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    booking: _Booking;
}): {
    id: string;
    booking: Booking;
} {
    return {
        id: value.id,
        booking: from_candid_Booking_n12(_uploadFile, _downloadFile, value.booking)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    name: string;
    pgId: string;
    user: Principal;
    phone: string;
    moveInDate: string;
    roomType: _RoomType;
}): {
    status: Variant_cancelled_pending_confirmed;
    name: string;
    pgId: string;
    user: Principal;
    phone: string;
    moveInDate: string;
    roomType: RoomType;
} {
    return {
        status: from_candid_variant_n14(_uploadFile, _downloadFile, value.status),
        name: value.name,
        pgId: value.pgId,
        user: value.user,
        phone: value.phone,
        moveInDate: value.moveInDate,
        roomType: value.roomType
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    verified: boolean;
    foodIncluded: boolean;
    wifiSpeed: bigint;
    owner: Principal;
    city: string;
    name: string;
    acAvailable: boolean;
    description: string;
    deposit: bigint;
    amenities: _Amenities;
    cleanlinessScore: number;
    availableBeds: bigint;
    longitude: number;
    address: _Address;
    gender: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    sharingTypes: Array<string>;
    foodScore: number;
    geoLocation: [] | [_GeoLocation];
    rooms: Array<_RoomType>;
    images: Array<string>;
}): {
    latitude: number;
    verified: boolean;
    foodIncluded: boolean;
    wifiSpeed: bigint;
    owner: Principal;
    city: string;
    name: string;
    acAvailable: boolean;
    description: string;
    deposit: bigint;
    amenities: Amenities;
    cleanlinessScore: number;
    availableBeds: bigint;
    longitude: number;
    address: Address;
    gender: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    sharingTypes: Array<string>;
    foodScore: number;
    geoLocation?: GeoLocation;
    rooms: Array<RoomType>;
    images: Array<string>;
} {
    return {
        latitude: value.latitude,
        verified: value.verified,
        foodIncluded: value.foodIncluded,
        wifiSpeed: value.wifiSpeed,
        owner: value.owner,
        city: value.city,
        name: value.name,
        acAvailable: value.acAvailable,
        description: value.description,
        deposit: value.deposit,
        amenities: value.amenities,
        cleanlinessScore: value.cleanlinessScore,
        availableBeds: value.availableBeds,
        longitude: value.longitude,
        address: value.address,
        gender: value.gender,
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        sharingTypes: value.sharingTypes,
        foodScore: value.foodScore,
        geoLocation: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.geoLocation)),
        rooms: value.rooms,
        images: value.images
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    address: [] | [_Address];
    gender: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    address?: Address;
    gender?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.address)),
        gender: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.gender)),
        phone: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): Variant_cancelled_pending_confirmed {
    return "cancelled" in value ? Variant_cancelled_pending_confirmed.cancelled : "pending" in value ? Variant_cancelled_pending_confirmed.pending : "confirmed" in value ? Variant_cancelled_pending_confirmed.confirmed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PGListing>): Array<PGListing> {
    return value.map((x)=>from_candid_PGListing_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Booking_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PGListing_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PGListing): _PGListing {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    verified: boolean;
    foodIncluded: boolean;
    wifiSpeed: bigint;
    owner: Principal;
    city: string;
    name: string;
    acAvailable: boolean;
    description: string;
    deposit: bigint;
    amenities: Amenities;
    cleanlinessScore: number;
    availableBeds: bigint;
    longitude: number;
    address: Address;
    gender: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    sharingTypes: Array<string>;
    foodScore: number;
    geoLocation?: GeoLocation;
    rooms: Array<RoomType>;
    images: Array<string>;
}): {
    latitude: number;
    verified: boolean;
    foodIncluded: boolean;
    wifiSpeed: bigint;
    owner: Principal;
    city: string;
    name: string;
    acAvailable: boolean;
    description: string;
    deposit: bigint;
    amenities: _Amenities;
    cleanlinessScore: number;
    availableBeds: bigint;
    longitude: number;
    address: _Address;
    gender: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    sharingTypes: Array<string>;
    foodScore: number;
    geoLocation: [] | [_GeoLocation];
    rooms: Array<_RoomType>;
    images: Array<string>;
} {
    return {
        latitude: value.latitude,
        verified: value.verified,
        foodIncluded: value.foodIncluded,
        wifiSpeed: value.wifiSpeed,
        owner: value.owner,
        city: value.city,
        name: value.name,
        acAvailable: value.acAvailable,
        description: value.description,
        deposit: value.deposit,
        amenities: value.amenities,
        cleanlinessScore: value.cleanlinessScore,
        availableBeds: value.availableBeds,
        longitude: value.longitude,
        address: value.address,
        gender: value.gender,
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        sharingTypes: value.sharingTypes,
        foodScore: value.foodScore,
        geoLocation: value.geoLocation ? candid_some(value.geoLocation) : candid_none(),
        rooms: value.rooms,
        images: value.images
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    address?: Address;
    gender?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    address: [] | [_Address];
    gender: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Variant_cancelled_pending_confirmed;
    name: string;
    pgId: string;
    user: Principal;
    phone: string;
    moveInDate: string;
    roomType: RoomType;
}): {
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        confirmed: null;
    };
    name: string;
    pgId: string;
    user: Principal;
    phone: string;
    moveInDate: string;
    roomType: _RoomType;
} {
    return {
        status: to_candid_variant_n10(_uploadFile, _downloadFile, value.status),
        name: value.name,
        pgId: value.pgId,
        user: value.user,
        phone: value.phone,
        moveInDate: value.moveInDate,
        roomType: value.roomType
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_confirmed): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == Variant_cancelled_pending_confirmed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_confirmed.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
